### ISSUE TITLE
unusual behavior in the image convergence

### ISSUE THREAD

**Issue by azrahello** [thoddnn/ComfyUI-MLX#5] opened 2024-10-12 09:26 UTC
There’s something wrong with image generation… there’s an unusual behavior in the image convergence. This happens when I make several generations and change something between one generation and another, like the model, the size of the latent, or some other variable. I even thought it might be related to the prompt. I also considered the possibility that it could be some kind of ‘protection’ for NSFW content that I might generate at times, but it doesn’t seem to be related to that. When this happens, performance also seems to degrade, with the time per iteration increasing dramatically, and memory usage as well. It feels like—though this is just my assumption, since I don’t really understand much about it—that it could be related to an accumulation of data from previous generations, as if there’s no proper flush happening, maybe with CLIP or something else. PS: With a restart, everything runs normally
I’m attaching an image with the result; it can be dragged onto ComfyUI to also see the prompt
![ComfyUI_00022_](https://github.com/user-attachments/assets/f5912a92-d7ba-4cb3-bcf0-2516de98de4e)
using base workflow

**Comment by jonny7737** [comment] 2024-10-14 15:23
I believe I have found the same issue. The initial workflow output is as expected - even if the workflow is run 100 times:
![Screenshot 2024-10-14 at 10 11 36 AM](https://github.com/user-attachments/assets/08db06bb-5da3-4794-b71d-b1b8980b6cfa)

After changing only the prompt, this is the output:
![Screenshot 2024-10-14 at 10 13 05 AM](https://github.com/user-attachments/assets/a0c6aa2b-f555-402d-b865-ecf4bb2644fe)

The person will never reapear in the image. At least not until the workflow is unloaded and reloaded OR the model and node cache is cleared.

**Comment by george7551858** [comment] 2024-10-16 04:09
Could reproduce by flux-schnell-4bit-quantized with Mac Mini M1 16G.

It's not just portraits, as long as the prompt is long enough and is run multiple times ( changing the prompt each time) you'll find problems.

The first image:
![image](https://github.com/user-attachments/assets/014c9cd9-edd8-486b-940e-e6ff84ebfc25)
and after a few generations:
![image](https://github.com/user-attachments/assets/cba267aa-f30a-4fe3-a472-76ec4a19a34a)

Using the "Unload Models" action could reset it.

**Comment by thoddnn** [comment] 2024-10-22 06:46
Hello everyone 👋

I have pushed a new update, and the issue should be resolved now. I can change prompt multiple times and no longer get this kind of result. 

To ensure you're running the latest version:

In ComfyUI, go to Manager > Install via Git URL, and use this URL:
https://github.com/thoddnn/ComfyUI-MLX.git

Since I have updated the input and output format (#4), you can use the new basic workflow available here:
https://github.com/thoddnn/ComfyUI-MLX/blob/main/workflows/basic_workflow.json

Please tell me if it is ok on your side 🙏

**Comment by jonny7737** [comment] 2024-10-22 15:03
It works for me and seems much faster start-to-finish.

**Comment by thoddnn** [comment] 2024-10-22 15:54
@jonny7737 Ok ,perfect. I close the issue.

Thanks again for your feedbacks @george7551858 @jonny7737 @azrahello 

More improvements are coming soon !

**Closed by thoddnn** 2024-10-22 15:54 UTC
